services:
    waaz_sylius_mondial_relay_plugin.admin.shipping_export:
      class: Waaz\SyliusMondialRelayPlugin\EventListener\MondialRelayShippingExportEventListener
      arguments:
          - '@waaz_sylius_mondial_relay_plugin.repository.pickup'
          - '@doctrine.orm.entity_manager'
      tags:
          - { name: kernel.event_listener, event: bitbag.export_shipment, method: exportShipment }

    waaz_sylius_mondial_relay_plugin.admin.shipping_gateway.update.javascripts:
        class: Sylius\Bundle\UiBundle\Block\BlockEventListener
        arguments:
            - '@@WaazSyliusMondialRelayPlugin/admin/gateway/edit/javascript.html.twig'
        tags:
            - { name: kernel.event_listener, event: sonata.block.event.bitbag.admin.shipping_gateway.update.javascripts, method: onBlockEvent }

    waaz_sylius_mondial_relay_plugin.admin.shipping_gateway.create.javascripts:
        class: Sylius\Bundle\UiBundle\Block\BlockEventListener
        arguments:
            - '@@WaazSyliusMondialRelayPlugin/admin/gateway/edit/javascript.html.twig'
        tags:
            - { name: kernel.event_listener, event: sonata.block.event.bitbag.admin.shipping_gateway.create.javascripts, method: onBlockEvent }

    waaz_sylius_mondial_relay_plugin.admin.layout.stylesheets:
        class: Sylius\Bundle\UiBundle\Block\BlockEventListener
        arguments:
            - '@@WaazSyliusMondialRelayPlugin/admin/stylesheets.html.twig'
        tags:
            - { name: kernel.event_listener, event: sonata.block.event.sylius.admin.layout.stylesheets, method: onBlockEvent }
